FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/java-producer-1.0.0.jar ./java-producer-1.0.0.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "java-producer-1.0.0.jar"]
